### ISSUE TITLE
Placeholder content

### ISSUE THREAD

**Issue by kkoch-revation** [DashboardCode/BsMultiSelect#10]
I was able to add a static placeholder via CSS:

ul.form-control::before {content: 'Placeholder ';}

From there you can style it however you like. Cheers.

**Comment by rpokrovskij** [comment]
Unclear. Use https://jsfiddle.net/u2xf6bew/3/ to demonstrate the issue.

**Comment by kkoch-revation** [comment]
No issue, but your documentation says no support for "placeholder" content. However I was able to include a placeholder using CSS as can be seen in this jsfiddle:
https://jsfiddle.net/kkoch/h3yceL0n/6/
Cheers!

**Comment by rpokrovskij** [comment]
OK :) I got it. Thank you! I will add this trick to docs or sample. Thank you again :)
