### ISSUE TITLE
Unable to select items.

### ISSUE THREAD

**Issue by edwolfe807** [DashboardCode/BsMultiSelect#14]
I have an ajax query that returns a json object.  One of the members of the json object of values to be selected in a multiselect box as follows:

`{"id":301,"member_sites":[1,100]}`

The following code is used to select the options:

```
var $memberSites = $('#editUserMemberSites');
$memberSites.val(user.member_sites);
```
This works for the following select box:

<select multiple="multiple" class="form-control" name="editUserMemberSites" id="editUserMemberSites" style="display: none;">
        <option value="1">Option 1/option>
        <option value="100">"B's" Option 2</option>
</select>

This works great (using standard multiple select) until I add the following code (then nothing is selected):
```
$('select[multiple]').bsMultiSelect({
        selectedPanelDefMinHeight: 'calc(2.25rem + 2px)',  // default size
        selectedPanelLgMinHeight: 'calc(2.875rem + 2px)',  // LG size
        selectedPanelSmMinHeight: 'calc(1.8125rem + 2px)', // SM size
        selectedPanelDisabledBackgroundColor: '#e9ecef',   // disabled background
        selectedPanelFocusBorderColor: '#80bdff',          // focus border
        selectedPanelFocusBoxShadow: '0 0 0 0.2rem rgba(0, 123, 255, 0.25)',  // foxus shadow
        selectedPanelFocusValidBoxShadow: '0 0 0 0.2rem rgba(40, 167, 69, 0.25)',  // valid foxus shadow
        selectedPanelFocusInvalidBoxShadow: '0 0 0 0.2rem rgba(220, 53, 69, 0.25)',  // invalid foxus shadow
        inputColor: '#495057', // color of keyboard entered text
        selectedItemContentDisabledOpacity: '.65' // btn disabled opacity used
    });
```

How do I properly select multiple options based on a json array with bsMultiSelect.  I've tried 5 or 10 ways to select the options including (but not limited to) using a selector to find the option with each value and set attr (also tried prop) selected.

nothing seem to work for selecting options.

**Comment by rpokrovskij** [comment]
BsMultuSelect is not designed to be used with ajax.  For ajax I'm using bloodhoud+typeahead. One day I will need to rewrite them, but now they covers the situation "find me an option on server side". 

BsMultiselect of course can imitate work with ajax by using such iteraction model: "dispose BsMultiselect; change original select according your goals, attach BsMultSelect again". It works quite well, BTW (no leaks, no crazy events) - at least was designed and tested (several versions ago :-) for it.

**Comment by edwolfe807** [comment]
Okay, then this is not useful to me.
