### ISSUE TITLE
Dynamic loading items

### ISSUE THREAD

**Issue by hitostacha** [DashboardCode/BsMultiSelect#2]
I'm trying to load data dynamically on the select, it loads smooth on the hidden one but it doesn't show in the snippet multiselect, are there any docs with information of this? I can't seem to find any.

**Comment by rpokrovskij** [comment]
jsfiddle please.

**Comment by rpokrovskij** [comment]
This was added to README.MD to issues.

> * no 'smart tracking' of dynamic changes in options - do detach/attach at the end of changes

**Comment by hitostacha** [comment]
> do destroy and attach after you have changed options dynamically - this should help in all cases. this is what I do.

Could you please ellaborate?
https://jsfiddle.net/hv03cnsx/30/
Also, sorry for the wait, here's the JSFiddle of basically what I'm trying to do, (I tried to simplify it as much as I could)
