### ISSUE TITLE
How to select options through code?

### ISSUE THREAD

**Issue by alex28012001** [DashboardCode/BsMultiSelect#20]
I just tried to add 'selected' attribute but it is not working, i think i need some refreshing or updating component

**Comment by alex28012001** [comment]
for future 
answer: $multiSelects.bsMultiSelect('UpdateData')

**Comment by rpokrovskij** [comment]
Yes, user should push changes with UpdateData or UpdateOptionsSelected  or with UpdateOptionSelected(index) for concreate option.  Synchronization there https://dashboardcode.github.io/BsMultiSelect/snippetJs.html   uses UpdateOptionSelected(index)

**Comment by rpokrovskij** [comment]
Also you can use SetOptionSelected(key, value) this should set "selected property" of the option element (but not attribute, if you need attribute you should setup/handle/override `setSelected` in the configuration).
