### ISSUE TITLE
Without BS!

### ISSUE THREAD

**Issue by marcelo-maciel** [DashboardCode/BsMultiSelect#22]
Hi Roman!

There is any way to use BsMultiSelect without BS4 or the best option, without any other external dependecy?
My current project use BS3.3.7

**Comment by rpokrovskij** [comment]
BS4 is not a dependency, (setup your css classes for BS3.3.7 e.g. in configuration)

```
$("select[multiple='multiple']").bsMultiSelect({
              useCssPatch=false, 
              css: {
                    // ...
              } ) 
```
BS4 values are in https://github.com/DashboardCode/BsMultiSelect/blob/master/js/src/BsCss.js use it as a sample.

Please share them there or on stackoverflow (BTW support my questions with ups on SO it will help me to give the answers) 

But popper.js V1 is a dependency. Fortunatly it works on many environments (and with BS3 also).  
If you want to replace popper.js with custom code - I could provide an interface for you.

**Comment by marcelo-maciel** [comment]
Thanks Roman!

**Comment by rpokrovskij** [comment]
I accept thanks there https://stackoverflow.com/users/506147/roman-pokrovskij?tab=questions as votes

**Comment by marcelo-maciel** [comment]
Done!
