### ISSUE TITLE
Language of validation message

### ISSUE THREAD

**Issue by marcelo-maciel** [DashboardCode/BsMultiSelect#23]
Hi Roman!

I'm developing a system with default language PT-BR, and html5 validation messages are fine, but with bsmultiselect, the message of required, for example, always show on english.
"Please select an item in the list".
If i remove the bsmultiselect, the messages are show correctly in Portuguese, "Selecione um item da lista.".

**Comment by rpokrovskij** [comment]
Check how it was done there: https://dashboardcode.github.io/BsMultiSelect/snippetRtl.html 
Here data-value-missing-message="ضروری" is used.  Alternatively you can use configuration 
`{valueMissingMessage="blabla"}`

**Comment by marcelo-maciel** [comment]
Thank's Roman!

**Comment by rpokrovskij** [comment]
> Thank'

Could I ask you to dublicatie your questions on Stackoverflow? I want to collect some expirience of tracking tag "bsmultiselect".
