### ISSUE TITLE
Choose different label colors

### ISSUE THREAD

**Issue by youbelo** [DashboardCode/BsMultiSelect#25]
Hello,
first, thank you very much for this amazing work.
I want to color my choosed labels (depending on color stored in data attribut) is it possible ?
thank you.

**Comment by rpokrovskij** [comment]
Thank you. Yes it is possible. Are you asking of coloring "dropdown itmes" or "selected picks"? 
I prefer to answer on such questions on SO. Can you dublicate your question on stackoverflow (there is a tag bsmultiselect)?

**Comment by youbelo** [comment]
done, thank you

**Comment by youbelo** [comment]
I posted the question in SO

**Comment by rpokrovskij** [comment]
Answered https://stackoverflow.com/questions/62192954/coloring-dropdown-itmes-and-selected-picks/62252399#62252399 , snippet provided
