### ISSUE TITLE
ReferenceError: adjustLegacySettings is not defined

### ISSUE THREAD

**Issue by dauthleikr** [DashboardCode/BsMultiSelect#26]
Hi, i'm trying to specify options, i'm using the ES6 module version. I'm using 0.6.2.

```javascript
import { BsMultiSelect } from '@dashboardcode/bsmultiselect/dist/js/BsMultiSelect.esm.min.js';

...

BsMultiSelect(element, environment, {
    placeholder:"select something.." // any option, does not matter
});
```

If I specify any options, I always get the error: `ReferenceError: adjustLegacySettings is not defined`.
Any idea?

**Comment by rpokrovskij** [comment]
Thank you for the report. Solved in 0.6.3 (available on npm).

Could I ask you to inform me why you are using ESM version? Do you have access to BS5 ?

**Comment by dauthleikr** [comment]
I tried using the jquery plugin version, but for whatever reason meteor did not play nice with it. The only way I got it to load propery was to hardcode a <script> tag, all usual ways of loading stuff failed. My guess is that meteor somehow messes up with it's module magic. I decided to not chase it down since I'm new to web development, it probably would have taken a long time, it doesn't matter for this small project and I do not intend to use meteor again anyways.

Thanks for the update by the way, works nicely!

**Comment by rpokrovskij** [comment]
@dauthleikr  Does it possible with meteor to reference source module directly ([BsMultiSelect.js](https://github.com/DashboardCode/BsMultiSelect/blob/master/js/src/BsMultiSelect.js) ) ? 

Then you will be able to load plugins only you need, confiugre babel transpiler as you need and remove all "defaults" and "settings" (of concrete instance) configuration garbage ( `defaults` in  https://github.com/DashboardCode/BsMultiSelect/blob/master/js/src/BsMultiSelect.esm.js )
