### ISSUE TITLE
Deselect all

### ISSUE THREAD

**Issue by marcelo-maciel** [DashboardCode/BsMultiSelect#28]
Hi Roman!

What is the best way to programatically desselect all itens?
And, there is any way to set the maximum selected itens?

Thanks!

**Comment by rpokrovskij** [comment]
1. One way `$('#edit-StatesPp-id').bsMultiSelect('DeselectAll')`
or if you have api object `api.deselectAll()`

2. What about "set the maximum selected items" in my expirience there are no one behaviour for all cases (e.g. user "just can't select" or "can select but become invalid, and if invalid is this involces HTML form validation status or just custom validation" ) so there are no "one simple option". 

Start coding passing custom `setSelected` that returns false when you want cancel user selection on your condition (exceed maximum selected items count).

Or you can allow selection but set custom or HTML validation status (check snippets). Or can combine both.

**Comment by rpokrovskij** [comment]
Create the Q on stackoverflow and I will reply with snippet how to use `custom HTML validation` (this is not the same as `custom validation`) for visualizing  maximum selected items condition.

**Comment by marcelo-maciel** [comment]
https://stackoverflow.com/questions/63407606/deselect-all-on-bsmultiselect

**Comment by rpokrovskij** [comment]
DeselectAll was illiustrated with sample. If you need snippet for "maximum selected items" then request for it in second SO question. Better in two new SO questions: one question for "do not allow to select more then" and "set and show invalidate if there are more then...".   "do not allow" and "validate" are two different behaviours. Actually SET IVALIDATE (html form status) and SHOW invalidate are also different behaviours.
