### ISSUE TITLE
doubt how can I customize the selected item? 

### ISSUE THREAD

**Issue by ko06** [DashboardCode/BsMultiSelect#3]
if I choose item its append to selected list with cross mark to remove icon. but i want just 

" 1 label selected" or "6 labels selected" message only.

**Comment by rpokrovskij** [comment]
It is possible to write your own adapter (overriding CreateSelectedItemContent ) but... 

BsMultiSelect is "input style" multi select, all its idea is to have items which look like text, to take an input focus and write filter "inline" as simple text, and use backspace to delete an item. So the idea to have option "6 labels selected" with "inline filter and backspase handled to delete an item" for this concreate plugin is contrproductive. . 

But thank you that you take a look on this one.
