### ISSUE TITLE
How to select options dinamically?

### ISSUE THREAD

**Issue by EdgarCsA** [DashboardCode/BsMultiSelect#30]
I use $("Id Name").value("listOptions") to select options in the box, but this only works when the page initialize. I need the options to being selected when, for example, I click a button. Do you have any suggestions?

**Comment by EdgarCsA** [comment]
I just found out the solution https://github.com/DashboardCode/BsMultiSelect/issues/5#issuecomment-513525502

**Comment by rpokrovskij** [comment]
#5 works but better use Options API. https://dashboardcode.github.io/BsMultiSelect/snippetJs.html . Shortly: after you have changed data you should inform BsMultiSelected about this events calling methogs: api.updateOptionSelected(index) : "push changes to the control".

If you would ask question on StackOverflow I could create a snippet for you
