### ISSUE TITLE
Select one option at a time on div

### ISSUE THREAD

**Issue by JulioCesarAntonyFraga** [DashboardCode/BsMultiSelect#32]
I was trying to use "setSelected" option on my multiselect, but I nnoticed that this does not work with divs (at least I couldn't reach it myself). I am trying to make two synced multiselects, using this example: https://dashboardcode.github.io/BsMultiSelect/snippetJs.html but with the last two inputs only.

Here's my code:

```html

    <label class="control-label" for="teste1-id">Teste1</label>
    <div id="teste1-id"></div>

    <label class="control-label" for="teste2-id">Teste2:</label>
    <div id="teste2-id"></div>

```

JavaScript:
```javascript
   var options = [


       { text: 'item1', value: 'item1'},
       { text: 'item2', value: 'item2'},

   ];


    var teste1 = null;
    var teste2 = null;
    let isTeste2 = true;
    var $testes = $('#teste1-id')
    if (isTeste2)
        $testes = $testes.add('#teste2-id')


    var install = function () {
        $testes.bsMultiSelect({
            options: options
        });
        if (isTeste2) {
            $('#teste1-id').on('dashboardcode.multiselect:change', function () {
                $('#teste2-id').bsMultiSelect("UpdateOptionsSelected");
            })
        }

    }
    install();
```

Could you help me find a solution, please?

**Comment by rpokrovskij** [comment]
Got it. Could you move your sample to https://codepen.io/rpokrovskij/pen/yLymQwW .
Stackoverflow snippet is also good option (there is a tag - I will see it).

**Comment by JulioCesarAntonyFraga** [comment]
> Got it. Could you move your sample to https://codepen.io/rpokrovskij/pen/yLymQwW ?
> Stackoverflow question with snippet is also good option (there is a tag bsmultiselect - I will see it).

Sure, I will figure out how to do it in a minute. Want me to delete this one?

**Comment by JulioCesarAntonyFraga** [comment]
> Got it. Could you move your sample to https://codepen.io/rpokrovskij/pen/yLymQwW ?
> Stackoverflow question with snippet is also good option (there is a tag bsmultiselect - I will see it).
Here is the question in the StackOverflow comunity. Thank you for the attention!
https://stackoverflow.com/questions/65816625/bsmultiselect-select-one-option-at-a-time-on-div

**Comment by rpokrovskij** [comment]
Moved to SO. At this time I do not see any problem with the code (but there are no setSelected call in the snippet)

**Comment by JulioCesarAntonyFraga** [comment]
> Moved to SO. At this time I do not see any problem with the code (but there are no setSelected call in the snippet) 

Yes, I didn't put that in the code above cus it didn't work when I tried it. Could u show me how to properly do it?

**Comment by rpokrovskij** [comment]
Yes of course, just append your snippet with the code that fails (and button "click me" to initiate an action )
