### ISSUE TITLE
IE 11 Support for two columns?

### ISSUE THREAD

**Issue by TdZink** [DashboardCode/BsMultiSelect#36]
Is there anything specific we have to do for it to render correctly in IE 11?
While it works having two columns makes it so the items do not render correct with the checkbox in front of each selection.

**Comment by rpokrovskij** [comment]
"two columns" functionality was realized though css. 
Just improove css if it doesn't work with IE 11. Or propose it to me I could show you how to embded it through configuration.
What css you need for which element?

**Comment by TdZink** [comment]
I am currently using the cssPatch option when calling the plugin.

 cssPatch: {
          choices: {columnCount: '2'}                   
        }
        
Renders great in Edge and Chrome. IE 11 is not correctly rendering checkbox for most of the items in the second column.

**Comment by rpokrovskij** [comment]
1. `columnCount: '2' ` means add `column-count: 2`  to the `ul` element ...  If IE 11 render it bad (I confirm it) there should be the workaround found: to add additional css to the elements UI or LI. 

2. Go to F12 find the `ul class="dropdown-menu"` change the style `display:none` to `display:block` and play with css and html to force the IE work correctly then send your results to me. 

Or  just use this snippet:

`````
<head>
		<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    			rel="stylesheet">
	</head>
	<body>
		<ul class="dropdown-menu"
  				style="left: 0px; top: 0px; display: block; list-style-type: none; position: absolute; column-count: 3 ; transform: translate3d(145px, 28px, 0px);"
  				x-placement="bottom-start">
				<li class="px-md-2 px-1">
					<div class="custom-control custom-checkbox d-flex"
   						style="justify-content: flex-start;">
						<input class="custom-control-input"
     							style="color: inherit;"
     							type="checkbox"
     							formnovalidate="">
							<label class="custom-control-label justify-content-start"
     								style="color: inherit;">Alabama</label>
						</div>
					</li>
				<li class="px-md-2 px-1">
						<div class="custom-control custom-checkbox d-flex"
   							style="justify-content: flex-start;">
							<input class="custom-control-input"
     								style="color: inherit;"
     								type="checkbox"
     								formnovalidate="">
								<label class="custom-control-label justify-content-start"
     									style="color: inherit;">Alaska</label>
							</div>
						</li>
				<li class="px-md-2 px-1">
							<div class="custom-control custom-checkbox d-flex"
   								style="justify-content: flex-start;">
								<input class="custom-control-input"
     									style="color: inherit;"
     									type="checkbox"
     									formnovalidate="">
									<label class="custom-control-label justify-content-start"
     										style="color: inherit;">Arizona</label>
								</div>
							</li>
		</ul>
	</body>
`````

As you see you should not bother about `BsMultiselect.css` - there are no such file and no custom css . All what is used only bootsrap.css and short inline css.  As it should: it render correctly in Chrome and doesn't in IE11. 

This is not BsMultiSelect specific...  If you find workaround I will show you to embded it to the BsMultiSelect  . Deal?

**Comment by rpokrovskij** [comment]
Stop. I've found that with latest version https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css it seems it works correctly.

**Comment by rpokrovskij** [comment]
just update BS to 4.6

**Comment by TdZink** [comment]
Switched to bootstrap 4.6 and the two columns render better. Thanks!
