### ISSUE TITLE
JS addEventListener is not triggering

### ISSUE THREAD

**Issue by TdZink** [DashboardCode/BsMultiSelect#37]
When I add addEventListener in my JS file for 'change' it never triggers when an option is selected. If I add inline 'onchange' in my HTML it works but I prefer to use event listeners in my JS file.

Is there a specific way I need to add the event listener in my JS file?

**Comment by rpokrovskij** [comment]
could you move this question to stakcoverflow with snippet?

**Comment by TdZink** [comment]
@rpokrovskij - Thank you.
I have posted my question to stackoverflow. 
https://stackoverflow.com/questions/67253844/js-addeventlistener-is-not-triggering

**Comment by rpokrovskij** [comment]
I see it but could you create working snippet with linked CDN libs?

**Comment by rpokrovskij** [comment]
BTW if you are interesting in injecting your code into bsmultiselect  - inject your function through configuration using setSelected parameter:

like  in sample from documentation:

   ```
       $('#mySelect').bsMultiSelect({
              setSelected: function(option /*element*/, value /*true|false*/){
                 // replace with you own code
                 // default is option.selected = value;
                  if (value) 
                      option.setAttribute('selected','');
                  else  
                      option.removeAttribute('selected');
                  option.selected = value;
                  // you can 'cancel' selecting returnin false
              }
          }); 
```

**Comment by TdZink** [comment]
@rpokrovskij - Thank you. I will work on getting a working code snippet in the stackoverflow post. If do not apply the bsmultiselect to the select element the event listener triggers which is what led me to the bsmultiselect as the cause of the event listener not triggering.

**Comment by rpokrovskij** [comment]
I do not fully understand your problem withou snippet. 

Anyway if you initialize the BsMultiSelect as jquery component I "guarentee" only that I call JQUERY 'change' envent (it is not the same as dom event) of the initial element (jquery convention).

**Comment by TdZink** [comment]
Thank you, @rpokrovskij . Using the jquery subscription worked so I can trigger my function whenever a value is selected/unselected.

**Comment by rpokrovskij** [comment]
Using you own `setSelected` you can trigger dom 'change' event. 
But there are no big sensce in this since you can do what you need in `setSelected` . for bsmultiselect the element is just a datastructure not more. datastructures usually  do not have events.  You update them wtih the functions (and this function can be passed to component - `setSelected` is such function).
