### ISSUE TITLE
Not able to use this

### ISSUE THREAD

**Issue by robertnicjoo** [DashboardCode/BsMultiSelect#4]
Hi,

Somehow I'm not able to use this package in my app,

# Code 

```
<div class="form">
  <h5>Tags <span class="text-danger">*</span></h5>
  <select name="tags[]" id="tags" class="tags chosen-select" multiple="multiple">
    <option value="" selected>Select</option>
    @foreach($tags as $tag)
        <option value="{{$tag->id}}">{{$tag->title}}</option>
    @endforeach
  </select>
</div>
```

```
<link rel="stylesheet" href="{{asset('css/BsMultiSelect.min.css')}}">
<script src="{{asset('js/BsMultiSelect.min.js')}}"></script>
<script>
    $(document).ready(function() {
        $('#tags').BsMultiSelect();
    });
</script>
```

# Output

![11](https://user-images.githubusercontent.com/8672823/46059583-19f60000-c18a-11e8-906c-3fa58a2c5229.png)

Any idea?

**Comment by rpokrovskij** [comment]
Thank you fro feedback.
Try to change name to be "simple identifier".

**Comment by rpokrovskij** [comment]
reusage of ids (for internal ids generation is changed). you still should not use not valid HTML4/5 ids and names, but if you have strong reasons for it you can provide your own ids generation functions. 

See the https://github.com/DashboardCode/BsMultiSelect/issues/16
