### ISSUE TITLE
Dropdown renders open on page load in IE 11

### ISSUE THREAD

**Issue by TdZink** [DashboardCode/BsMultiSelect#40]
Running bootstrap 4.6 did fix the issue with having multiple columns but I have been able to figure out a solution for the dropdown rendering open on page load in IE 11.

**Comment by rpokrovskij** [comment]
I need snippet.

Here is my sample. Dropdown renders cloded...
https://dashboardcode.github.io/BsMultiSelect/snippetColumns.html

**Comment by TdZink** [comment]
Thank you, for your response. It appears to happen when I have the following line in my JS:
$("#tagSelect").bsMultiSelect("UpdateData");

**Comment by rpokrovskij** [comment]
Here is the snippet: https://dashboardcode.github.io/BsMultiSelect/snippetJsSimpleUpdateData.html . There is UpdateData on startup and I do not observe the "open dropdown" on IE11 . Could you adjust it to your scenario?

**Comment by rpokrovskij** [comment]
@TdZink solved in ver 1.1.1 (for bioth BS4 and BS5 target bundles, actualy Bootstrap 5 by itself doesn't support IE11).
reason was that setup of placeholder throws input event on IE11.
