### ISSUE TITLE
Bug in JQueryMethodsPlugin

### ISSUE THREAD

**Issue by jstark518** [DashboardCode/BsMultiSelect#43]
https://github.com/DashboardCode/BsMultiSelect/blob/3d71514a53c88743043752e69bb000e93127f682/js/src/plugins/JQueryMethodsPlugin.js#L12

Call to undefined picksDom.

I was able to fix this by adding 'picksDom = pluginData.picksDom,'

**Comment by rpokrovskij** [comment]
Thank you. Going to release new version today.
