### ISSUE TITLE
How to trigger updateAppearance() method from other scripts?

### ISSUE THREAD

**Issue by CrestApps** [DashboardCode/BsMultiSelect#46]
I have 3 menus (a, b, c) that works as a drilldown. In other words, menu `a` is populated when the page is loaded. However, menu `b` is populated after menu `a` change and has values (the values from a are used to populate b.) Then when menu `b` changes, menu `c` is populated. Since these menu options are dynamically loaded, the `updateAppearance()` needs to be called each time a change event is fired!

I want to be able to reuse the code that populates the drilldown menus. So, I want to make sure that the drilldown logic stays independent of BsMultiSelect. In other cases, I am using the same drilldown logic without BsMultiSelect.

In addition to the bsMultiSelect code, I added the following code to activate it using css-class. So my `bsMultiSelect.js` look like this
```
// Here I am also including the BsMultiSelect code.

let menus = document.getElementsByClassName('content-picker');

for (let i = 0; i < menus.length; i++) {
    let menu = menus[i];
    var bsMenu = dashboardcode.BsMultiSelect(menu, {
        placeholder: menus[i].getAttribute('placeholder') || '',
        useChoicesDynamicStyling: true, 
        cssPatch: {
            choices: { columnCount: menu.getAttribute('data-column-count') || '1' },
        },
        useHighlighting: true
    });

    // save an instance of the bsMenu as a property on the element to be updated later
    menu.bsMenu = bsMenu;
}
```

Then in another file called `drilldown.js` I have a function that populates the items in the menu, that looks something like this

```
function populateMenu(select, url) {

    clearMenu(select);

    fetch(url, {
        method: 'get'
    }).then(response => response.json())
        .then(jsonData => {
            for (let i = 0; i < jsonData.length; i++) {
                let item = jsonData[i];
                let opt = document.createElement('option');

                if (!item.text) {
                    continue;
                }
                opt.value = item.value;
                opt.innerHTML = item.text;

                select.appendChild(opt);
            }

            select.removeAttribute('disabled');
            dispatchChange(select, eventType);

            if (select.bsMenu) {
                // at this point we know that this menu is a bsMenu, lets update its appearance
                // this does not work!
               console.log('Fixing sppearance for menu with id ' + select.id);
                select.bsMenu.updateAppearance();
            }
        })
        .catch(err => {
            console.log(err);
        });
}

```

As you can see in the above code, I am checking to see if `select.bsMenu` is set, and if so I want to fire `select.bsMenu.updateAppearance();`. But in this case it does not work. I do see the log to the console as expected, but `select.bsMenu.updateAppearance();` does not really do anything. I confiremed that the `populateMenu` function actually appends the options to the menu correctly. but `select.bsMenu.updateAppearance();` does not seem to have effect in my case.

I am loading the scripts in the following order
```
drilldown.js
bsMultiSelect.js
```

The `drilldown.js` must be loaded first as it has the listeners to the `change` events. Is this an issue or something I am doing wrong here?

**Comment by rpokrovskij** [comment]
I'm not sure that I'm able to understand this with witout snippet. Create snippet and ask it through stackOverflow (there are tag for bsMultiSelect). I wll reply you in SO.

P.S. One thing I can say ahead: updateAppearance updates only "validity" and "size" (push changes from bs custom vlidity and size css classes ). it seems like you want to is data - use udateData for it.

**Comment by CrestApps** [comment]
@rpokrovskij Thank you! Calling  `select.bsMenu.updateData();` instead worked!
