### ISSUE TITLE
Append more and selected option using jquery 

### ISSUE THREAD

**Issue by sovoeun** [DashboardCode/BsMultiSelect#5]
I have issue when i use jQuery to append more and selected option but it append only select box but doesn't append new option on BsMultiSelect
i use code below:
` $('#other').append("<option value='5' selected>Testing</option>");`

Please help?

**Comment by rpokrovskij** [comment]
Dispose plugin, add/remove items, create it once more.

**Comment by sillyfrog** [comment]
For other newbies like me looking to update the values on the fly with jquery/javascript, this is what I found works for me, for example:
```
$("#edit-states1-id").bsMultiSelect("Dispose");
$("#edit-states1-id").val([ "IL", "IA", "PA" ]);
$("#edit-states1-id").bsMultiSelect();
```
