### ISSUE TITLE
Update with 0.2.22 and got error

### ISSUE THREAD

**Issue by Noido** [DashboardCode/BsMultiSelect#6]
Uncaught TypeError: $(...).bsMultiSelect is not a function
When i use import '@dashboardcode/bsmultiselect/dist/js/BsMultiSelect.js';

and it  was working before you update in 0.2.22

thanks for your help

**Comment by rpokrovskij** [comment]
Check your bundle - find jquery or bsMultiSelect loading code, there should be wrong pathes isn't it?

Try to remove node_modules and package-lock.json and run `node install`.  

This should help you but I need to say that I do not fully understand how webpack/node calculate all dependencies and that means I'm not sure that BsMultiSelect's package.json is correct enough. If smb understand why webpack sometimes create absurdist imports - please give us a direction how to increase stability.

**Comment by Noido** [comment]
I have update Jquery in 3.4 and it works now

Thanks
